POST http://stele.dynv6.net/api_jsonrpc.php
content-type: application/json

{
    "jsonrpc": "2.0",
    "method": "hostgroup.get",
    "params": {
        "output":["groupid"],
        "filter": {"name": ["STE"]}
    },
    "auth": "f966696902a5a33273847d647d1d479c26e330325ba7ba421c350bf837c08ca9",
    "id": 1
}

###
POST http://stele.dynv6.net/api_jsonrpc.php
content-type: application/json

{
    "jsonrpc": "2.0",
    "method": "template.get",
    "params": {
        "output": ["templateid"],
        "filter": {"name": ["Xerox Phaser 6130N"]}
    },
    "auth": "f966696902a5a33273847d647d1d479c26e330325ba7ba421c350bf837c08ca9",
    "id": 1
}

###
POST http://stele.dynv6.net/api_jsonrpc.php
content-type: application/json

{
    "jsonrpc": "2.0",
    "method": "item.get",
    "params": {
        "output":["key_"],
        "host": "000000000",
        "filter": {"type": 2}
    },
    "auth": "f966696902a5a33273847d647d1d479c26e330325ba7ba421c350bf837c08ca9",
    "id": 1
}

###
POST http://stele.dynv6.net/api_jsonrpc.php
content-type: application/json

{
    "jsonrpc": "2.0",
    "method": "host.get",
    "params": {
        "output":["hostid", "host", "name"],
        "filter": { "host": ["000000000"] },
        "selectTags": "extend"
    },
    "auth": "f966696902a5a33273847d647d1d479c26e330325ba7ba421c350bf837c08ca9",
    "id": 1
}

###
POST http://stele.dynv6.net/api_jsonrpc.php
content-type: application/json

{
    "jsonrpc": "2.0",
    "method": "host.get",
    "params": {
        "output": ["host", "name"],
        "selectTags": "extend",
        "tags": [
            {
                "tag": "agentId",
                "value": "216bdf99-0284-4717-8b8d-9d9471ad1a8e",
                "operator": 0
            }
        ]
    },
    "auth": "f966696902a5a33273847d647d1d479c26e330325ba7ba421c350bf837c08ca9",
    "id": 1
}

###
POST http://stele.dynv6.net/api_jsonrpc.php
content-type: application/json

{
    "jsonrpc": "2.0",
    "method": "host.create",
    "params": {
        "host": "000000000",
        "name": "STEFANO Xerox Phaser 6130N casa 000000000",
        "templates": [{"templateid": "10435"}],
        "groups": [{"groupid": "20"}]
    },
    "auth": "f966696902a5a33273847d647d1d479c26e330325ba7ba421c350bf837c08ca9",
    "id": 1
}