; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName LAC_agent
#define MyAppVersion 5.0.0.0
#define MyAppPublisher Stefano Pompa
#define MyAppURL http://stefanopompa.blogspot.com
;#define MyAppExeName lac.cmd

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{A5197861-69FA-43C4-B5C6-383DE8E45A94}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
VersionInfoVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName=C:\{#MyAppName}
DisableDirPage=yes
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
OutputDir=C:\Users\stefa\Documents\GitHub\lac\agent
OutputBaseFilename=lac_agent
Compression=lzma
SolidCompression=yes

[Languages]
Name: italian; MessagesFile: compiler:Languages\Italian.isl

[Files]
Source: C:\Users\stefa\Documents\GitHub\lac\agent\net-snmp-5.5.0-2.x64.exe; DestDir: {app}; Flags: ignoreversion
Source: C:\Users\stefa\Documents\GitHub\lac\agent\zabbix_agent-5.2.3-windows-amd64-openssl\bin\zabbix_agentd.exe; DestDir: {app}; Flags: ignoreversion
Source: C:\Users\stefa\Documents\GitHub\lac\agent\zabbix_agent-5.2.3-windows-amd64-openssl\bin\zabbix_sender.exe; DestDir: {app}; Flags: ignoreversion
Source: C:\Users\stefa\Documents\GitHub\lac\agent\lac_inst.cmd; DestDir: {app}; Flags: ignoreversion
Source: C:\Users\stefa\Documents\GitHub\lac\agent\lac_uninst.cmd; DestDir: {app}; Flags: ignoreversion
Source: C:\Users\stefa\Documents\GitHub\lac\agent\lac.pdf; DestDir: {app}; Flags: ignoreversion
; NOTE: Don't use Flags: ignoreversion on any shared system files

[Icons]
;Name: {group}\{#MyAppName}; Filename: {app}\{#MyAppExeName}
Name: {group}\{cm:ProgramOnTheWeb,{#MyAppName}}; Filename: {#MyAppURL}
Name: {group}\{cm:UninstallProgram,{#MyAppName}}; Filename: {uninstallexe}

[Run]
Filename: {app}\lac_inst.cmd;

[UninstallRun]
Filename: {app}\lac_uninst.cmd;

[UninstallDelete]
Type: filesandordirs; Name: C:\{#MyAppName};
Type: filesandordirs; Name: C:\usr;